Feature 1
Hauwa-Sambo/Travel-website pull request #1
Opened 2024-10-06 20:14 UTC by Hauwa-Sambo

Designed a responsive travel landing page using Figma design template.

2024-10-08 12:37 UTC, Xfarouq commented on index.html
> +    </section>
Always make sure your indentation is well

2024-10-08 12:38 UTC, Xfarouq commented on style.css
> +width: 356px;
Always be mindful of your indentations

2024-10-08 12:49 UTC, Xfarouq requested changes
Hi @Hauwa-Sambo 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Your design isn't the same as the figma, below are some areas you can focus on 
![Screenshot 2024-10-08 134618](https://github.com/user-attachments/assets/abbfc32a-ad83-4ca1-95e7-aca188613880)
![Screenshot 2024-10-08 134456](https://github.com/user-attachments/assets/8dbce66c-d65c-4dfb-b880-d0f788d105f1)


### Optional Suggestions

- Make sure to not leave spaces in your code for best practice
- Always be mindful of your indentations

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-13 16:04 UTC, Devsalmasaeed requested changes

2024-10-13 16:04 UTC, Devsalmasaeed commented on index.html
> +                </a>
Be mindful of Html semantic
<section id ="destination">
       <div class="destination grid">
             <div class="mirror">
                     <img>
                      <h4></h4>
                      <p></p>
            </div>
     </div>

2024-10-13 16:04 UTC, Devsalmasaeed commented on style.css
> +
> Hi @Hauwa-Sambo
> 
> Good job so far! You still need to work on some issues to get your project approved, but you are almost there!
> 
> ![Remote Collaboration](https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)
> ### To Highlight 💯
> * **Clean code** 👍
> * **Good use of Gitflow** 👍
> * **Implemented some project requirements** 👍
> 
> ### Required Changes ♻️
> * Make sure to have professional PR title
> * Your design isn't the same as the figma, below are some areas you can focus on
> ![Step 2 screenshot](https://images.tango.us/workflows/ea62b2b5-c97d-4612-beee-40037d0c1c23/steps/9e31b014-b506-4101-95bb-c481993139ba/0995e656-e21d-4dd6-aa2b-a88e7320c7f9.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n)
> ### Optional Suggestions
> * Always be mindful of your indentations
> 
> Cheers and Happy coding! 👏👏👏
> 
> _Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification._

2024-10-18 20:14 UTC, Xfarouq approved these changes
..A

2024-10-18 20:14 UTC, Xfarouq approved these changes
Hi @Hauwa-Sambo,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    <img src="https://media1.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa8sx12d824xrvy8zo8bq3w00f23hoj11gqqzus7q0f&ep=v1_gifs&rid=giphy.gif&ct=g" alt="Remote Collaboration" style="width:100%;">
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**
- ✅ **Nice use of semantic classes to render API elements**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-18 20:22 UTC, Xfarouq approved these changes
Hi @Hauwa-Sambo 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

List the changes that need to be fixed.
For example,

- kindly consider having the app's name on the splash screen as requested in the project requirement or as given on the design

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-19 17:45 UTC, merged